# Generated by Django 5.2.8 on 2025-11-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banner',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
